Metrics/AbcSize:
  Max: 1000 # no max

Metrics/CyclomaticComplexity:
  Max: 1000 # no max

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 1000 # no max

Metrics/ParameterLists:
  Max: 1000 # no max

Metrics/PerceivedComplexity:
  Max: 1000 # no max
